### ISSUE TITLE
기능목록

### ISSUE THREAD

**Issue by jaemoon-sim** [euihyun-lee/webtoon-collection#1]
기능 목록을 정리합니다.
크게 `회원 CRUD`, `즐겨찾기 CRUD`, `만화 CRUD`, `크롤링` 정도로 구분되지 싶습니다.

**Comment by jaemoon-sim** [comment]
## CRUD API
Restful하게 

### READ
- 엔드포인트 `GET URL/user/{user_id}`, `GET URL/toon/{toon_id}`, `GET URL/star/{star_id}`
- `id`에 해당하는 정보 read


### CREATE
- 엔드포인트 `POST URL/user`, `POST URL/toon`, `POST URL/star`
    - return `user_id`, `toon_id`, `star_id`
- 새로운 user, toon, 즐찾 아이디 return

### UPDATE
- 엔드포인트 `PUT URL/user/{user_id}`, `PUT URL/toon/{toon_id}`, `PUT URL/star/{star_id}`
- `id`에 해당하는 이미 있는 정보 변경
    - 없는 경우 에러반환

### DELETE
- 엔드포인트 `DELETE URL/user/{user_id}`, `DELETE URL/toon/{toon_id}`, `DELETE URL/star/{star_id}`
- 정보 삭제
    - 이미 DB에 없는 경우에도 return true

**Comment by euihyun-lee** [comment]
#3 에서 episode 하고 view_history가 추가되었으니, 각각에 대한 CRUD도 만들어야 할듯 합니다.

**Comment by euihyun-lee** [comment]
## CRUD 이외의 API

#### `GET URL/unseen/user/{user_id}`
- `user_id`를 가지는 `user`가 `star`한 `toon`의 `episode` 중 보지 않은 것을 시간순으로 정렬하여 records return
#### `GET URL/browse/{platform_name}?weekday={day_representation}`
- 해당 `weekday`에 연재하는 `toon` 중 해당 `platform_name`에서 연재하는 `toon`들 및 이들의 최신 `episode` records return
- `weekday` 미지정 시 모든 `toon`에 대해서 `episode` records return
#### `GET URL/thumbnail/toon/{toon_id}`
- `toon_id`에 해당하는 썸네일 이미지 return
#### `GET URL/thumbnail/episode/{episode_id}`
- `episode_id`에 해당하는 썸네일 이미지 return

**Comment by euihyun-lee** [comment]
## CRUD API (자세하게)
### READ
#### `GET URL/user/{user_id}`
* `id`에 해당하는 record return
#### `GET URL/user/{user_id}/star?weekday={day_representation}`
- `user_id`를 가지는 `user`가 `star`한 `toon` 중, 해당 `weekday`에 연재하는 `toon`들 및 이들의 최신 `episode` records return
- `weekday` 미지정 시 `weekday`에 관계없이 관련 records return
#### `GET URL/user/{user_id}/toon/{toon_id}/star`
- `user_id`, `toon_id`를 FK로 가지는 `star`들의 record return
#### `GET URL/user/{user_id}/history`
- `user_id`를 FK로 가지는 `view_history`들의 record return

#### `GET URL/toon`
* 모든 `toon` record return
#### `GET URL/toon/{toon_id}`
* `id`에 해당하는 record return
* (선택) 해당 `toon`의 `star` 개수 또한 return
#### `GET URL/toon/{toon_id}/episode`
- `toon_id`를 FK로 가지는 `episode`들의 record return

#### `GET URL/star/{star_id}`
* `id`에 해당하는 record return

#### `GET URL/episode/{episode_id}`
* `id`에 해당하는 record return
#### `GET URL/episode/{episode_id}/history`
- `episode_id`를 FK로 가지는 `view_history`들의 record return

### CREATE
만들어진 record의 `id` return
#### `POST URL/user`
* Request body
```yaml
{
    "user_id": ID,
    "pw": password,
    "name": name
}
```

#### `POST URL/toon`
* Request body
```yaml
{
    "title": title,
    "synopsis": synopsis,
    "platform": platform_name,
    "weekday": day_representation,
    "url": url,
    "thumbnail_url": thumbnail_url
}
```

#### `POST URL/star`
* Request body
```yaml
{
    "user_id": user_id,
    "toon_id": toon_id
}
```

#### `POST URL/episode`
* Request body
```yaml
{
    "toon_id": toon_id,
    "title": title,
    "url": url,
    "thumbnail_url": thumbnail_url
}
```

#### `POST URL/history`
* Request body
```yaml
{
    "user_id": user_id,
    "episode_id": episode_id
}
```

### UPDATE
없는 `id`일 경우 에러 반환
#### `PUT URL/user/{user_id}`
* Request body
```yaml
{
    "pw": password,
    "name": name
}
```

#### `PUT URL/toon/{toon_id}`
* Request body
```yaml
{
    "title": title,
    "synopsis": synopsis,
    "platform": platform_name,
    "weekday": day_representation,
    "url": url,
    "thumbnail_url": thumbnail_url
}
```

#### `PUT URL/star/{star_id}`
* Request body
```yaml
{
    "user_id": user_id,
    "toon_id": toon_id
}
```

#### `PUT URL/episode/{episode_id}`
* Request body
```yaml
{
    "toon_id": toon_id,
    "sequence": sequence_number,
    "title": title,
    "url": url,
    "thumbnail_url": thumbnail_url
}
```

#### `PUT URL/history/{history_id}`
* Request body
```yaml
{
    "user_id": user_id,
    "episode_id": episode_id
}
```

### DELETE
이미 DB에 없어도 `True` 반환
#### `DELETE URL/user/{user_id}`
#### `DELETE URL/toon/{toon_id}`
#### `DELETE URL/star/{star_id}`
#### `DELETE URL/episode/{episode_id}`
#### `DELETE URL/history/{history_id}`
